version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5439:5432/tcp
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql